#!/bin/bash
if [ -z "$1" ]
	then
		echo "Please provide the IP Address..."
		exit 1
fi

ifconfig wlan0 down
iwconfig wlan0 mode ad-hoc
iwconfig wlan0 essid bbk
ifconfig wlan0 $1 netmask 255.255.255.0
ifconfig wlan0 up
